apiVersion: v1
kind: Pod
metadata:
  name: phi-rocm-pod
spec:
  containers:
    - name: phi-container
      image: quay.io/mtahhan/qwen-demo:latest
      imagePullPolicy: Never
      command: ["./entrypoint-qwen.sh"]
      ports:
        - containerPort: 8000
      env:
        - name: MODEL
          value: "RedHatAI/phi-4"
        - name: PORT
          value: "8000"
        - name: MODE
          value: "serve"
        - name: VLLM_USE_COMPILED_ATTENTION
          value: "1"
        - name: VLLM_COMPILED_ATTENTION_BACKEND
          value: "1"
        - name:  VLLM_USE_V1
          value: "1"
        - name:  HUGGING_FACE_HUB_TOKEN
          value: "XXX"
      resources:
        limits:
          amd.com/gpu: 1
      securityContext:
        privileged: true
  restartPolicy: Never
