apiVersion: v1
kind: Pod
metadata:
  name: qwen-rocm-pod
spec:
  containers:
    - name: qwen-container
      image: quay.io/mtahhan/qwen-demo:latest
      command: ["./entrypoint-qwen.sh"]
      ports:
        - containerPort: 8000
      env:
        - name: MODEL
          value: "Qwen/Qwen1.5-0.5B"
        - name: PORT
          value: "8000"
        - name: MODE
          value: "serve"
        - name: VLLM_USE_COMPILED_ATTENTION
          value: "1"
        - name: VLLM_COMPILED_ATTENTION_BACKEND
          value: "1"
        - name:  VLLM_USE_V1
          value: "1"
      resources:
        limits:
          amd.com/gpu: 1
      securityContext:
        privileged: true
  restartPolicy: Never
