apiVersion: v1
kind: Pod
metadata:
  name: qwen-rocm-pod
spec:
  containers:
    - name: qwen-container
      image: quay.io/mtahhan/qwen-demo:latest
      command: ["./entrypoint-qwen.sh"]
      ports:
        - containerPort: 8000
      env:
        - name: MODEL
          value: "Qwen/Qwen1.5-0.5B"
        - name: PORT
          value: "8000"
        - name: MODE
          value: "serve"
      resources:
        limits:
          amd.com/gpu: 1  # Assumes AMD GPU resource name is amd.com/gpu
      securityContext:
        privileged: true
  restartPolicy: Never
