apiVersion: v1
kind: Pod
metadata:
  name: qwen-rocm-cache-pod
spec:
  restartPolicy: Never
  volumes:
    - name: triton-cache-volume
      emptyDir: {}

  initContainers:
    - name: tcv-init
      image: quay.io/mtahhan/tcv:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          echo "Running Triton Cache Vault (TCV)..."
          /tcv -e -i quay.io/mtahhan/qwen-rocm-cache:latest -d /home/vllm/.cache/vllm/

          echo "Extracted cache in /home/vllm/.cache/vllm/..."
          ls -al /home/vllm/.cache/vllm/
      env:
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        - name: HOME
          value: "/home/vllm"
      volumeMounts:
        - name: triton-cache-volume
          mountPath: /home/vllm/.cache/vllm/
      securityContext:
        privileged: false
        capabilities:
          add:
            - SYS_ADMIN
        seccompProfile:
          type: Unconfined
      resources:
        limits:
          amd.com/gpu: 1

  containers:
    - name: qwen-container
      image: quay.io/mtahhan/qwen-demo:latest
      ports:
        - containerPort: 8000
      env:
        - name: HOME
          value: "/home/vllm"
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        - name: MODEL
          value: "Qwen/Qwen1.5-0.5B"
        - name: VLLM_USE_COMPILED_ATTENTION
          value: "1"
        - name: VLLM_COMPILED_ATTENTION_BACKEND
          value: "1"
        - name:  VLLM_USE_V1
          value: "1"
      volumeMounts:
        - name: triton-cache-volume
          mountPath: /home/vllm/.cache/vllm/
      resources:
        limits:
          amd.com/gpu: 1
      securityContext:
        privileged: true
