apiVersion: v1
kind: Pod
metadata:
  name: triton-pod
  labels:
    purpose: demo-triton
spec:
  restartPolicy: Never  # <-- moved here!
  containers:
    - name: triton-container
      image: quay.io/mtahhan/rocm-demo:latest
      workingDir: /workspace
      env:
        - name: HIP_VISIBLE_DEVICES
          value: "0"
      command: ["/bin/bash", "-c"]
      args: ["/entrypoint.sh && python /workspace/triton-flash-attention.py && tail -f /dev/null"]
      securityContext:
        privileged: true
      resources:
        limits:
          amd.com/gpu: 1
