apiVersion: v1
kind: Pod
metadata:
  name: triton-cache-pod
  labels:
    purpose: demo-triton-cache
spec:
  restartPolicy: Never
  volumes:
    - name: triton-cache-volume
      emptyDir: {}

  initContainers:
    - name: tcv-init
      image: quay.io/mtahhan/tcv
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          echo "Running Triton Cache Vault (TCV)..."
          /tcv -e -i quay.io/mtahhan/flash-attention-rocm:latest

          echo "Extracted cache in /workspace/.triton/cache..."
          ls -al /workspace/.triton/cache
      env:
        - name: TRITON_CACHE_DIR
          value: "/workspace/.triton/cache"
        - name: TRITON_HOME
          value: "/workspace/"
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        - name: HOME
          value: "/workspace"
      volumeMounts:
        - name: triton-cache-volume
          mountPath: /workspace/.triton/cache
      securityContext:
        privileged: false
        capabilities:
          add:
            - SYS_ADMIN
        seccompProfile:
          type: Unconfined
      resources:
        limits:
          amd.com/gpu: 1

  containers:
    - name: triton-container
      image: quay.io/mtahhan/rocm-demo:latest
      workingDir: /workspace
      env:
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        - name: HOME
          value: "/workspace"
        - name: TRITON_CACHE_DIR
          value: "/workspace/.triton/cache"
        - name: TRITON_HOME
          value: "/workspace/"
      command: ["/bin/bash", "-c"]
      args: ["/entrypoint.sh && ls -al /workspace/.triton/cache && python /workspace/triton-flash-attention.py && tail -f /dev/null"]
      securityContext:
        privileged: true
      resources:
        limits:
          amd.com/gpu: 1
      volumeMounts:
        - name: triton-cache-volume
          mountPath: /workspace/.triton/cache
