apiVersion: v1
kind: Pod
metadata:
  name: triton-pod
  labels:
    purpose: demo-triton
spec:
  volumes:
    - name: rocm-runtime
      emptyDir: {}

  initContainers:
    - name: rocm-build-env-installer
      image: registry.access.redhat.com/ubi9/ubi-minimal
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          echo "[ROCm]" > /etc/yum.repos.d/rocm.repo
          echo "name=ROCm" >> /etc/yum.repos.d/rocm.repo
          echo "baseurl=https://repo.radeon.com/rocm/rhel9/6.2/main" >> /etc/yum.repos.d/rocm.repo
          echo "enabled=1" >> /etc/yum.repos.d/rocm.repo
          echo "gpgcheck=0" >> /etc/yum.repos.d/rocm.repo

          microdnf install -y gcc gcc-c++ make cmake python3.11 python3.11-devel \
              amd-smi-lib amd-smi miopen-hip rocm-core rocm-hip-libraries \
              rocminfo llvm clang lld numactl-libs gcc gcc-c++ cmake make && \
          mkdir -p /rocm-runtime && \
          cp -a /opt/rocm /rocm-runtime/opt_rocm && \
          cp -a /usr/include/python3.11 /rocm-runtime/include_python3.11 && \
          cp -a /usr/lib64/libpython3.11* /rocm-runtime/lib/ && \
          cp -a /usr/bin/gcc /rocm-runtime/bin/ && \
          cp -a /usr/bin/g++ /rocm-runtime/bin/ && \
          cp -a /usr/lib64/libgomp* /rocm-runtime/lib/ && \
          cp -a /usr/lib64/libstdc++* /rocm-runtime/lib/ && \
          microdnf clean all
      volumeMounts:
        - mountPath: /rocm-runtime
          name: rocm-runtime

  containers:
    - name: triton-container
      image: quay.io/mtahhan/rocm-demo:latest
      workingDir: /workspace
      env:
        - name: HIP_VISIBLE_DEVICES
          value: "0"
        - name: LD_LIBRARY_PATH
          value: "/rocm-runtime/lib:/rocm-runtime/opt_rocm/llvm/lib:/usr/lib64:/usr/lib"
        - name: PATH
          value: "/opt/venv/bin:/rocm-runtime/bin:/rocm-runtime/opt_rocm/bin:/rocm-runtime/opt_rocm/llvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: ROCM_PATH
          value: "/rocm-runtime/opt_rocm"
      command: ["/bin/bash", "-c", "--"]
      args: ["/entrypoint.sh; python3 /workspace/triton-vector-add-rocm.py"]
      volumeMounts:
        - mountPath: /rocm-runtime
          name: rocm-runtime
      resources:
        limits:
          amd.com/gpu: 1
