apiVersion: v1
kind: Pod
metadata:
  name: triton-pod
  labels:
    purpose: demo-triton
spec:
  containers:
    - name: triton-container
      image: quay.io/mtahhan/rocm-demo:latest
      workingDir: /workspace
      env:
      - name: HIP_VISIBLE_DEVICES
        value: "0" # # 0,1,2,...,n for running on GPU and select the GPUs, -1 for running on CPU
      command: ["/bin/bash", "-c", "--"]
      args: ["python3 /workspace/triton-vector-add-rocm.py"]
      resources:
        limits:
          amd.com/gpu: 1 # requesting a GPU
